using AIVS.Data;
using AIVS.Models.ViewModels.Reports;
using AIVS.Models.ViewModels.UserManagement;
using AIVS.Services.Interface;
using AIVS.Security;
using ClosedXML.Excel;
using System.Drawing;
using Microsoft.EntityFrameworkCore;

namespace AIVS.Services.Implementations
{
    public class StatsExtractService : IStatsExtractService
    {
        private readonly AttributesDbContext _context;
        private readonly IAivsRoleAccessService _roleAccess;

        public StatsExtractService(AttributesDbContext context, IAivsRoleAccessService roleAccess)
        {
            _context = context;
            _roleAccess = roleAccess;
        }

        public async Task<byte[]> BuildExecutiveStatsExtractAsync(
            AivsCurrentUserVm currentUser,
            ExecutiveStatsExtractFilterVm filter)
        {
            if (!_roleAccess.HasPermission(currentUser, AivsPermission.ExportStatistics))
                throw new InvalidOperationException("You do not have permission to export executive stats.");

            var dateRange = ResolveDateRange(filter);

            var fromDate = dateRange.FromDate.Date;
            var toDateExclusive = dateRange.ToDate.Date.AddDays(1);

            var rows = await _context.AttrPropertyInfo
                .AsNoTracking()
                .Where(x =>
                    x.IsActive == true &&
                    (
                        (x.UpdatedDate != null && x.UpdatedDate >= fromDate && x.UpdatedDate < toDateExclusive) ||
                        (x.UpdatedDate == null && x.SubmissionDateTime >= fromDate && x.SubmissionDateTime < toDateExclusive)
                    ))
                .Select(x => new ExecutiveStatsRow
                {
                    AttrId = x.Attr_ID,
                    AttrNo = x.Attr_No,
                    PropertyDescription = x.Property_Desc,
                    PropertyType = x.Property_Type,
                    PremiseId = x.Premise_id,
                    Sector = x.RoutedSector ?? x.Sector,
                    Status = x.Attr_Status,

                    SubmittedByName = x.SubmittedByName,
                    SubmittedByEmail = x.SubmittedByEmail,
                    SubmissionDateTime = x.SubmissionDateTime,

                    AssignedTo = x.Task_Assigned_To,
                    AssignedToUserId = x.Task_Assigned_To_UserId,
                    AssignedDateTime = x.Task_Assigned_DateTime,

                    Valuer = x.Valuer,
                    ValuerUserId = x.ValuerUserId,
                    ValuerDecision = x.ValuerDecision,
                    ValuerDecisionDateTime = x.ValuerDecisionDateTime,

                    PhysicalInspectionRequired = x.Physical_Inspection_Required,
                    PhysicalInspectionStatus = x.Physical_Inspection_Status,
                    InspectionScheduledDate = x.Inspection_Scheduled_Date,
                    InspectionScheduledTime = x.Inspection_Scheduled_Time,
                    InspectionOutcome = x.Inspection_Outcome,

                    ReadyForOvvioExtract = x.ReadyForOvvioExtract,
                    OvvioExtractStatus = x.OvvioExtractStatus,
                    OvvioExtractBatchNo = x.OvvioExtractBatchNo,
                    OvvioExtractDateTime = x.OvvioExtractDateTime,

                    EvidenceCount = x.Evidence_Count,
                    IsWithdrawn = x.IsWithdrawn,

                    CreatedDate = x.CreatedDate,
                    UpdatedDate = x.UpdatedDate
                })
                .OrderBy(x => x.Sector)
                .ThenBy(x => x.Valuer)
                .ThenBy(x => x.AttrNo)
                .ToListAsync();

            using var workbook = new XLWorkbook();

            BuildSummarySheet(workbook, rows, filter.PeriodType, fromDate, dateRange.ToDate, currentUser);
            BuildStatusSheet(workbook, rows);
            BuildSectorSheet(workbook, rows);
            BuildValuerSheet(workbook, rows);
            BuildDetailSheet(workbook, rows);

            using var stream = new MemoryStream();
            workbook.SaveAs(stream);

            return stream.ToArray();
        }

        private static void BuildSummarySheet(
            XLWorkbook workbook,
            List<ExecutiveStatsRow> rows,
            string periodType,
            DateTime fromDate,
            DateTime toDate,
            AivsCurrentUserVm currentUser)
        {
            var ws = workbook.Worksheets.Add("Summary");

            ws.Cell(1, 1).Value = "AIVS Executive Stats Extract";
            ws.Cell(1, 1).Style.Font.Bold = true;
            ws.Cell(1, 1).Style.Font.FontSize = 16;

            ws.Cell(3, 1).Value = "Period Type";
            ws.Cell(3, 2).Value = periodType;

            ws.Cell(4, 1).Value = "From Date";
            ws.Cell(4, 2).Value = fromDate.ToString("yyyy-MM-dd");

            ws.Cell(5, 1).Value = "To Date";
            ws.Cell(5, 2).Value = toDate.ToString("yyyy-MM-dd");

            ws.Cell(6, 1).Value = "Generated By";
            ws.Cell(6, 2).Value = currentUser.FullName;

            ws.Cell(7, 1).Value = "Generated Date";
            ws.Cell(7, 2).Value = DateTime.Now.ToString("yyyy-MM-dd HH:mm");

            var startRow = 10;

            ws.Cell(startRow, 1).Value = "Metric";
            ws.Cell(startRow, 2).Value = "Total";

            ws.Range(startRow, 1, startRow, 2).Style.Font.Bold = true;
            ws.Range(startRow, 1, startRow, 2).Style.Fill.BackgroundColor = XLColor.LightGray;

            var metrics = new List<(string Label, int Count)>
            {
                ("Total Records", rows.Count),
                ("Sector Inbox", CountStatus(rows, "SectorInbox")),
                ("Claimed", CountStatus(rows, "Claimed")),
                ("Under Review", CountStatus(rows, "ValuerReview")),
                ("Inspection Required", CountStatus(rows, "InspectionRequired")),
                ("Inspection Confirmed", CountStatus(rows, "InspectionConfirmed")),
                ("Inspection Details Sent", CountStatus(rows, "InspectionDetailsSent")),
                ("Inspection Expired", CountStatus(rows, "InspectionExpired")),
                ("Returned To Client", CountStatus(rows, "ReturnedToClient")),
                ("Ready For OVVIO Extract", CountStatus(rows, "ReadyForOvvioExtract")),
                ("Senior Manager QA", CountStatus(rows, "SeniorManagerQa")),
                ("Rejected", CountStatus(rows, "Rejected")),
                ("Withdrawn", rows.Count(x => x.IsWithdrawn == true))
            };

            var rowNo = startRow + 1;

            foreach (var metric in metrics)
            {
                ws.Cell(rowNo, 1).Value = metric.Label;
                ws.Cell(rowNo, 2).Value = metric.Count;
                rowNo++;
            }

            ws.Columns().AdjustToContents();
        }

        private static void BuildStatusSheet(
            XLWorkbook workbook,
            List<ExecutiveStatsRow> rows)
        {
            var ws = workbook.Worksheets.Add("Status Breakdown");

            ws.Cell(1, 1).Value = "Status";
            ws.Cell(1, 2).Value = "Total";

            ws.Range(1, 1, 1, 2).Style.Font.Bold = true;
            ws.Range(1, 1, 1, 2).Style.Fill.BackgroundColor = XLColor.LightGray;

            var data = rows
                .GroupBy(x => string.IsNullOrWhiteSpace(x.Status) ? "Unknown" : x.Status.Trim())
                .Select(g => new
                {
                    Status = g.Key,
                    Total = g.Count()
                })
                .OrderByDescending(x => x.Total)
                .ToList();

            var rowNo = 2;

            foreach (var item in data)
            {
                ws.Cell(rowNo, 1).Value = item.Status;
                ws.Cell(rowNo, 2).Value = item.Total;
                rowNo++;
            }

            ws.Columns().AdjustToContents();
        }

        private static void BuildSectorSheet(
            XLWorkbook workbook,
            List<ExecutiveStatsRow> rows)
        {
            var ws = workbook.Worksheets.Add("Sector Stats");

            var headers = new[]
            {
                "Sector",
                "Total",
                "Sector Inbox",
                "Claimed",
                "Under Review",
                "Inspection Required",
                "Inspection Confirmed",
                "Inspection Details Sent",
                "Inspection Expired",
                "Returned",
                "Ready OVVIO",
                "Rejected"
            };

            WriteHeaders(ws, headers);

            var data = rows
                .GroupBy(x => string.IsNullOrWhiteSpace(x.Sector) ? "Unknown" : x.Sector.Trim())
                .Select(g => new
                {
                    Sector = g.Key,
                    Total = g.Count(),
                    SectorInbox = g.Count(x => IsStatus(x.Status, "SectorInbox")),
                    Claimed = g.Count(x => IsStatus(x.Status, "Claimed")),
                    UnderReview = g.Count(x => IsStatus(x.Status, "ValuerReview")),
                    InspectionRequired = g.Count(x => IsStatus(x.Status, "InspectionRequired")),
                    InspectionConfirmed = g.Count(x => IsStatus(x.Status, "InspectionConfirmed")),
                    InspectionDetailsSent = g.Count(x => IsStatus(x.Status, "InspectionDetailsSent")),
                    InspectionExpired = g.Count(x => IsStatus(x.Status, "InspectionExpired")),
                    Returned = g.Count(x => IsStatus(x.Status, "ReturnedToClient")),
                    ReadyOvvio = g.Count(x => IsStatus(x.Status, "ReadyForOvvioExtract")),
                    Rejected = g.Count(x => IsStatus(x.Status, "Rejected"))
                })
                .OrderBy(x => x.Sector)
                .ToList();

            var rowNo = 2;

            foreach (var item in data)
            {
                ws.Cell(rowNo, 1).Value = item.Sector;
                ws.Cell(rowNo, 2).Value = item.Total;
                ws.Cell(rowNo, 3).Value = item.SectorInbox;
                ws.Cell(rowNo, 4).Value = item.Claimed;
                ws.Cell(rowNo, 5).Value = item.UnderReview;
                ws.Cell(rowNo, 6).Value = item.InspectionRequired;
                ws.Cell(rowNo, 7).Value = item.InspectionConfirmed;
                ws.Cell(rowNo, 8).Value = item.InspectionDetailsSent;
                ws.Cell(rowNo, 9).Value = item.InspectionExpired;
                ws.Cell(rowNo, 10).Value = item.Returned;
                ws.Cell(rowNo, 11).Value = item.ReadyOvvio;
                ws.Cell(rowNo, 12).Value = item.Rejected;
                rowNo++;
            }

            ws.Columns().AdjustToContents();
        }

        private static void BuildValuerSheet(
            XLWorkbook workbook,
            List<ExecutiveStatsRow> rows)
        {
            var ws = workbook.Worksheets.Add("Valuer Stats");

            var headers = new[]
            {
                "Valuer",
                "Valuer UserId",
                "Sector",
                "Total Assigned",
                "Claimed",
                "Under Review",
                "Inspection Required",
                "Inspection Confirmed",
                "Inspection Details Sent",
                "Inspection Expired",
                "Returned",
                "Ready OVVIO",
                "Rejected"
            };

            WriteHeaders(ws, headers);

            var data = rows
                .Where(x =>
                    !string.IsNullOrWhiteSpace(x.AssignedToUserId) ||
                    !string.IsNullOrWhiteSpace(x.ValuerUserId))
                .GroupBy(x => new
                {
                    UserId = !string.IsNullOrWhiteSpace(x.ValuerUserId)
                        ? x.ValuerUserId
                        : x.AssignedToUserId,

                    Name = !string.IsNullOrWhiteSpace(x.Valuer)
                        ? x.Valuer
                        : x.AssignedTo,

                    Sector = x.Sector
                })
                .Select(g => new
                {
                    Valuer = string.IsNullOrWhiteSpace(g.Key.Name) ? "Unknown Valuer" : g.Key.Name!,
                    UserId = g.Key.UserId,
                    Sector = g.Key.Sector,
                    Total = g.Count(),
                    Claimed = g.Count(x => IsStatus(x.Status, "Claimed")),
                    UnderReview = g.Count(x => IsStatus(x.Status, "ValuerReview")),
                    InspectionRequired = g.Count(x => IsStatus(x.Status, "InspectionRequired")),
                    InspectionConfirmed = g.Count(x => IsStatus(x.Status, "InspectionConfirmed")),
                    InspectionDetailsSent = g.Count(x => IsStatus(x.Status, "InspectionDetailsSent")),
                    InspectionExpired = g.Count(x => IsStatus(x.Status, "InspectionExpired")),
                    Returned = g.Count(x => IsStatus(x.Status, "ReturnedToClient")),
                    ReadyOvvio = g.Count(x => IsStatus(x.Status, "ReadyForOvvioExtract")),
                    Rejected = g.Count(x => IsStatus(x.Status, "Rejected"))
                })
                .OrderBy(x => x.Valuer)
                .ToList();

            var rowNo = 2;

            foreach (var item in data)
            {
                ws.Cell(rowNo, 1).Value = item.Valuer;
                ws.Cell(rowNo, 2).Value = item.UserId;
                ws.Cell(rowNo, 3).Value = item.Sector;
                ws.Cell(rowNo, 4).Value = item.Total;
                ws.Cell(rowNo, 5).Value = item.Claimed;
                ws.Cell(rowNo, 6).Value = item.UnderReview;
                ws.Cell(rowNo, 7).Value = item.InspectionRequired;
                ws.Cell(rowNo, 8).Value = item.InspectionConfirmed;
                ws.Cell(rowNo, 9).Value = item.InspectionDetailsSent;
                ws.Cell(rowNo, 10).Value = item.InspectionExpired;
                ws.Cell(rowNo, 11).Value = item.Returned;
                ws.Cell(rowNo, 12).Value = item.ReadyOvvio;
                ws.Cell(rowNo, 13).Value = item.Rejected;
                rowNo++;
            }

            ws.Columns().AdjustToContents();
        }

        private static void BuildDetailSheet(
            XLWorkbook workbook,
            List<ExecutiveStatsRow> rows)
        {
            var ws = workbook.Worksheets.Add("Detail");

            var headers = new[]
            {
                "Attr_ID",
                "Attr_No",
                "Property Description",
                "Property Type",
                "Premise ID",
                "Sector",
                "Status",
                "Submitted By",
                "Submitted Email",
                "Submitted Date",
                "Assigned To",
                "Assigned UserId",
                "Assigned Date",
                "Valuer",
                "Valuer UserId",
                "Valuer Decision",
                "Valuer Decision Date",
                "Physical Inspection Required",
                "Physical Inspection Status",
                "Inspection Scheduled Date",
                "Inspection Scheduled Time",
                "Inspection Outcome",
                "Ready For OVVIO",
                "OVVIO Status",
                "OVVIO Batch No",
                "OVVIO Extract Date",
                "Evidence Count",
                "Withdrawn",
                "Created Date",
                "Updated Date"
            };

            WriteHeaders(ws, headers);

            var rowNo = 2;

            foreach (var item in rows)
            {
                ws.Cell(rowNo, 1).Value = item.AttrId;
                ws.Cell(rowNo, 2).Value = item.AttrNo;
                ws.Cell(rowNo, 3).Value = item.PropertyDescription;
                ws.Cell(rowNo, 4).Value = item.PropertyType;
                ws.Cell(rowNo, 5).Value = item.PremiseId;
                ws.Cell(rowNo, 6).Value = item.Sector;
                ws.Cell(rowNo, 7).Value = item.Status;
                ws.Cell(rowNo, 8).Value = item.SubmittedByName;
                ws.Cell(rowNo, 9).Value = item.SubmittedByEmail;
                ws.Cell(rowNo, 10).Value = item.SubmissionDateTime;
                ws.Cell(rowNo, 11).Value = item.AssignedTo;
                ws.Cell(rowNo, 12).Value = item.AssignedToUserId;
                ws.Cell(rowNo, 13).Value = item.AssignedDateTime;
                ws.Cell(rowNo, 14).Value = item.Valuer;
                ws.Cell(rowNo, 15).Value = item.ValuerUserId;
                ws.Cell(rowNo, 16).Value = item.ValuerDecision;
                ws.Cell(rowNo, 17).Value = item.ValuerDecisionDateTime;

                ws.Cell(rowNo, 28).Value = item.PhysicalInspectionRequired.HasValue
? item.PhysicalInspectionRequired.Value
: string.Empty;
                ws.Cell(rowNo, 19).Value = item.PhysicalInspectionStatus;
                ws.Cell(rowNo, 20).Value = item.InspectionScheduledDate;
                ws.Cell(rowNo, 21).Value = item.InspectionScheduledTime?.ToString();
                ws.Cell(rowNo, 22).Value = item.InspectionOutcome;

                ws.Cell(rowNo, 28).Value = item.ReadyForOvvioExtract.HasValue
    ? item.ReadyForOvvioExtract.Value
    : string.Empty;
                ws.Cell(rowNo, 24).Value = item.OvvioExtractStatus;
                ws.Cell(rowNo, 25).Value = item.OvvioExtractBatchNo;
                ws.Cell(rowNo, 26).Value = item.OvvioExtractDateTime;
                ws.Cell(rowNo, 27).Value = item.EvidenceCount;
                ws.Cell(rowNo, 28).Value = item.IsWithdrawn.HasValue
      ? item.IsWithdrawn.Value
      : string.Empty;
                ws.Cell(rowNo, 29).Value = item.CreatedDate;
                ws.Cell(rowNo, 30).Value = item.UpdatedDate;
                rowNo++;
            }

            ws.Columns().AdjustToContents();
        }

        private static void WriteHeaders(IXLWorksheet ws, string[] headers)
        {
            for (var i = 0; i < headers.Length; i++)
            {
                ws.Cell(1, i + 1).Value = headers[i];
            }

            ws.Range(1, 1, 1, headers.Length).Style.Font.Bold = true;
            ws.Range(1, 1, 1, headers.Length).Style.Fill.BackgroundColor = XLColor.LightGray;
            ws.SheetView.FreezeRows(1);
        }

        private static (DateTime FromDate, DateTime ToDate) ResolveDateRange(
            ExecutiveStatsExtractFilterVm filter)
        {
            var today = DateTime.Today;

            if (string.Equals(filter.PeriodType, "Weekly", StringComparison.OrdinalIgnoreCase))
            {
                var diff = ((int)today.DayOfWeek + 6) % 7;
                var monday = today.AddDays(-diff);
                var sunday = monday.AddDays(6);

                return (monday, sunday);
            }

            if (string.Equals(filter.PeriodType, "Monthly", StringComparison.OrdinalIgnoreCase))
            {
                var firstDay = new DateTime(today.Year, today.Month, 1);
                var lastDay = firstDay.AddMonths(1).AddDays(-1);

                return (firstDay, lastDay);
            }

            if (filter.FromDate == null || filter.ToDate == null)
                throw new InvalidOperationException("From date and To date are required for a custom extract.");

            if (filter.FromDate.Value.Date > filter.ToDate.Value.Date)
                throw new InvalidOperationException("From date cannot be later than To date.");

            return (filter.FromDate.Value.Date, filter.ToDate.Value.Date);
        }

        private static int CountStatus(List<ExecutiveStatsRow> rows, string status)
        {
            return rows.Count(x => IsStatus(x.Status, status));
        }

        private static bool IsStatus(string? value, string status)
        {
            return Clean(value) == Clean(status);
        }

        private static string Clean(string? value)
        {
            return string.IsNullOrWhiteSpace(value)
                ? string.Empty
                : value.Trim().ToUpperInvariant();
        }

        private class ExecutiveStatsRow
        {
            public long AttrId { get; set; }

            public string? AttrNo { get; set; }

            public string? PropertyDescription { get; set; }

            public string? PropertyType { get; set; }

            public string? PremiseId { get; set; }

            public string? Sector { get; set; }

            public string? Status { get; set; }

            public string? SubmittedByName { get; set; }

            public string? SubmittedByEmail { get; set; }

            public DateTime SubmissionDateTime { get; set; }

            public string? AssignedTo { get; set; }

            public string? AssignedToUserId { get; set; }

            public DateTime? AssignedDateTime { get; set; }

            public string? Valuer { get; set; }

            public string? ValuerUserId { get; set; }

            public string? ValuerDecision { get; set; }

            public DateTime? ValuerDecisionDateTime { get; set; }

            public bool? PhysicalInspectionRequired { get; set; }

            public string? PhysicalInspectionStatus { get; set; }

            public DateTime? InspectionScheduledDate { get; set; }

            public TimeSpan? InspectionScheduledTime { get; set; }

            public string? InspectionOutcome { get; set; }

            public bool? ReadyForOvvioExtract { get; set; }

            public string? OvvioExtractStatus { get; set; }

            public string? OvvioExtractBatchNo { get; set; }

            public DateTime? OvvioExtractDateTime { get; set; }

            public int? EvidenceCount { get; set; }

            public bool? IsWithdrawn { get; set; }

            public DateTime CreatedDate { get; set; }

            public DateTime? UpdatedDate { get; set; }



        }
    }
}
